name = "seotax_next"
license = "MIT"
licenselink = "https://github.com/varofla/hugo-seotax/blob/next/LICENSE"
description = "Personal Hugo theme for varofla.com"
homepage = "https://github.com/varofla/hugo-seotax"
demosite = ""
tags = ["responsive", "post", "search", "taxonomy", "pagination", "mobile"]
features = ["search", "two-level categories", "image zoom"]
min_version = "0.146.0"

[editor]
  name = "varofla"
  homepage = "https://github.com/varofla/"
